# Generated by Django 2.2.7 on 2020-01-18 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermorefields',
            name='timestampExp',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermorefields',
            name='timestampNow',
            field=models.CharField(default=14, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermorefields',
            name='token',
            field=models.CharField(default=17, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermorefields',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
