# Generated by Django 2.2.7 on 2019-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrazAll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
    ]
