# Generated by Django 2.2.7 on 2019-11-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrazAll',
            new_name='GrazShop',
        ),
    ]
