# Generated by Django 2.2.7 on 2019-11-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191121_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrazShop',
        ),
    ]
