# Generated by Django 2.2.7 on 2019-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191122_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('search_name', models.CharField(max_length=255)),
                ('search_category', models.CharField(max_length=255)),
                ('search_poi', models.CharField(max_length=255)),
                ('search_radius', models.IntegerField()),
            ],
        ),
    ]
