# Generated by Django 2.2.7 on 2019-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191122_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavourite',
            name='id',
            field=models.AutoField(default=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
