# Generated by Django 2.2.7 on 2019-11-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191122_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavourite',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
