# Generated by Django 2.2.7 on 2019-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191122_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourite',
            name='id',
            field=models.IntegerField(blank=True, default=True, primary_key=True, serialize=False),
        ),
    ]
