# Generated by Django 2.2.7 on 2019-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191122_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourite',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
