# Generated by Django 2.2.7 on 2019-11-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191122_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavourite',
            old_name='id',
            new_name='idd',
        ),
    ]
