# Generated by Django 2.2.7 on 2019-11-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191122_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavourite',
        ),
    ]
