# Generated by Django 2.2.7 on 2019-11-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userfavourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourite',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
