# Generated by Django 2.2.7 on 2019-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191122_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grazpoi',
            name='id',
            field=models.CharField(default=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grazshop',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
